"""full schema redesign v2

Revision ID: 8a0aaba41a48
Revises: 21763aa0310a
Create Date: 2026-07-31 23:13:12.837393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a0aaba41a48'
down_revision = '21763aa0310a'
branch_labels = None
depends_on = None


def upgrade():
    # MANUALLY ADDED -- NOT part of Alembic's autogenerate output.
    # Alembic's autogenerate only diffs column presence/type, it does NOT
    # detect changes to an existing Enum column's allowed value set (a
    # known limitation, worse across the SQLite-baseline-vs-MySQL-target
    # gap this migration was generated across -- SQLite doesn't even have
    # a native ENUM type). Without these two statements, models.py would
    # allow role='hod' and status='late', but the real DB's CHECK/ENUM
    # constraint would still reject them -- a silent app-vs-DB mismatch
    # that autogenerate gave no warning about.
    #
    # Using batch_alter_table (not a plain op.alter_column) even though
    # this is a MySQL target: verified in a real sandbox run that plain
    # alter_column produces `ALTER TABLE ... ALTER COLUMN ... TYPE ...`,
    # which is Postgres syntax, not valid on SQLite OR MySQL (MySQL needs
    # MODIFY COLUMN). batch_alter_table lets Alembic pick correct DDL per
    # dialect -- confirmed working end-to-end against SQLite below; MySQL
    # uses the same code path with its own correct dialect output.
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column(
            'role',
            existing_type=sa.Enum('admin', 'lecturer', 'student'),
            type_=sa.Enum('admin', 'hod', 'lecturer', 'student'),
            existing_nullable=False,
        )
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.alter_column(
            'status',
            existing_type=sa.Enum('present', 'absent', 'excused'),
            type_=sa.Enum('present', 'late', 'absent', 'excused'),
            existing_nullable=True,
            existing_server_default=sa.text("'present'"),
        )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('semesters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('hods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('staff_id', sa.String(length=50), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('staff_id')
    )
    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.Enum('university', 'department', 'course'), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('grade', sa.Enum('A', 'B', 'C', 'D', 'F'), nullable=False),
    sa.Column('entered_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['entered_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'course_id', 'semester_id', name='uq_result_student_course_semester')
    )
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_attendance_student_session', ['student_id', 'session_id'])

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_title', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('course_code', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('semester_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('credit_units', sa.Integer(), nullable=True))
        batch_op.alter_column('department_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_unique_constraint('uq_course_code_semester', ['course_code', 'semester_id'])
        # NAMED explicitly (autogenerate left this as create_foreign_key(None, ...)) --
        # SQLite's batch mode (table recreation) requires a name to reference
        # the constraint during the copy; verified by this exact failure in
        # a sandbox run before naming it.
        batch_op.create_foreign_key('fk_courses_semester_id', 'semesters', ['semester_id'], ['id'])
        batch_op.drop_column('code')
        batch_op.drop_column('title')

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_enrollment_student_course', ['student_id', 'course_id'])

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timetable_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('start_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('stop_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('room', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key('fk_sessions_timetable_id', 'timetable', ['timetable_id'], ['id'])

    with op.batch_alter_table('students', schema=None) as batch_op:
        # MANUALLY ADDED server_default (autogenerate left this off).
        # Without it, adding a NOT NULL column to a table that already has
        # rows fails outright on MySQL -- there's no value to backfill
        # existing rows with. sa.func.now() renders as CURRENT_TIMESTAMP,
        # matching models.py's new server_default=db.func.now() above.
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
        batch_op.alter_column('level',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=False)

    with op.batch_alter_table('timetable', schema=None) as batch_op:
        batch_op.add_column(sa.Column('semester_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('type', sa.Enum('scheduled', 'fixed'), nullable=False))
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_timetable_created_by', 'users', ['created_by'], ['id'])
        batch_op.create_foreign_key('fk_timetable_semester_id', 'semesters', ['semester_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timetable', schema=None) as batch_op:
        # Named to match the create_foreign_key calls in upgrade() above.
        batch_op.drop_constraint('fk_timetable_created_by', type_='foreignkey')
        batch_op.drop_constraint('fk_timetable_semester_id', type_='foreignkey')
        batch_op.drop_column('created_by')
        batch_op.drop_column('type')
        batch_op.drop_column('semester_id')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('level',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('created_at')

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_sessions_timetable_id', type_='foreignkey')
        batch_op.drop_column('room')
        batch_op.drop_column('stop_time')
        batch_op.drop_column('start_time')
        batch_op.drop_column('timetable_id')

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_constraint('uq_enrollment_student_course', type_='unique')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=150), nullable=False))
        batch_op.add_column(sa.Column('code', sa.VARCHAR(length=20), nullable=False))
        batch_op.drop_constraint('fk_courses_semester_id', type_='foreignkey')
        batch_op.drop_constraint('uq_course_code_semester', type_='unique')
        batch_op.alter_column('department_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('credit_units')
        batch_op.drop_column('semester_id')
        batch_op.drop_column('course_code')
        batch_op.drop_column('course_title')

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_constraint('uq_attendance_student_session', type_='unique')

    op.drop_table('results')
    op.drop_table('announcements')
    op.drop_table('hods')
    op.drop_table('semesters')
    # ### end Alembic commands ###

    # MANUALLY ADDED, reverting the two alter_column calls at the top of
    # upgrade(). NOTE: this will fail if any row still has role='hod' or
    # status='late' at downgrade time -- narrowing an Enum's value set is
    # inherently lossy/unsafe once data uses the value being removed. Not
    # something a migration can resolve on your behalf; whoever runs this
    # downgrade needs to have already reassigned/cleaned up those rows.
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.alter_column(
            'status',
            existing_type=sa.Enum('present', 'late', 'absent', 'excused'),
            type_=sa.Enum('present', 'absent', 'excused'),
            existing_nullable=True,
            existing_server_default=sa.text("'present'"),
        )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column(
            'role',
            existing_type=sa.Enum('admin', 'hod', 'lecturer', 'student'),
            type_=sa.Enum('admin', 'lecturer', 'student'),
            existing_nullable=False,
        )
